name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  WEBAPP_NAME: identificeren
  WEBAPP_PACKAGE_PATH: '.'      # Project Path Location default to root(.)

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Install zip
      run: dotnet tool install dotnet-zip
    - name: Create nuget folder
      run: mkdir nuget
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet publish
    - name: Zip
      run: dotnet zip -o app.zip '${{ env.WEBAPP_PACKAGE_PATH }}/src/IdentityServer4/src/bin/Debug/netcoreapp3.1/publish/'
    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.WEBAPP_NAME }} 
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_2CA027B81BB0434BAAB4A949469E8C3A  }} 
        package: '.'
